# Generated by Django 2.2.3 on 2019-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GearSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spec', models.CharField(help_text='Enter all get-sets separated by space.\nYou can also use', max_length=1024)),
            ],
        ),
    ]
