# Generated by Django 2.2.3 on 2019-07-30 05:38

from django.db import migrations, models
import gearset.models


class Migration(migrations.Migration):

    dependencies = [
        ('gearset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearset',
            name='spec',
            field=models.TextField(help_text='Enter all gear-sets separated by space.\nYou can also use a "-" to specify range.', max_length=1024, validators=[gearset.models.validate_gearset_spec]),
        ),
    ]
